# Generated by Django 3.2.9 on 2023-10-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image',
        ),
    ]
