# Generated by Django 3.2.9 on 2023-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_remove_memo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
