# Generated by Django 4.2.6 on 2023-10-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
